# Generated by Django 3.2.23 on 2024-02-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_plugin_turnitin', '0002_alter_turnitinsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnitinsubmission',
            name='ora_submission_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
