# Generated by Django 3.2.23 on 2024-02-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_plugin_turnitin", "0003_turnitinsubmission_ora_submission_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnitinsubmission",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
